openapi: 3.0.0
info:
  version: 2017-07-25
  x-release: v4
  title: Amazon Lookout for Metrics ActivateAnomalyDetector ListAnomalyGroupTimeSeries API
  description: This is the <i>Amazon Lookout for Metrics API Reference</i>. For an introduction to the service with tutorials for getting started, visit <a href="https://docs.aws.amazon.com/lookoutmetrics/latest/dev">Amazon Lookout for Metrics Developer Guide</a>.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: lookoutmetrics
  x-aws-signingName: lookoutmetrics
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/lookoutmetrics-2017-07-25.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://lookoutmetrics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The LookoutMetrics multi-region endpoint
- url: https://lookoutmetrics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The LookoutMetrics multi-region endpoint
- url: http://lookoutmetrics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The LookoutMetrics endpoint for China (Beijing) and China (Ningxia)
- url: https://lookoutmetrics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The LookoutMetrics endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListAnomalyGroupTimeSeries
paths:
  /ListAnomalyGroupTimeSeries:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListAnomalyGroupTimeSeries
      description: Gets a list of anomalous metrics for a measure in an anomaly group.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAnomalyGroupTimeSeriesResponse'
        '480':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - AnomalyDetectorArn
              - AnomalyGroupId
              - MetricName
              properties:
                AnomalyDetectorArn:
                  description: The Amazon Resource Name (ARN) of the anomaly detector.
                  type: string
                  pattern: arn:([a-z\d-]+):.*:.*:.*:.+
                  maxLength: 256
                AnomalyGroupId:
                  description: The ID of the anomaly group.
                  type: string
                  pattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
                  maxLength: 63
                MetricName:
                  description: The name of the measure field.
                  type: string
                  pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
                  maxLength: 256
                MaxResults:
                  description: The maximum number of results to return.
                  type: integer
                  minimum: 1
                  maximum: 100
                NextToken:
                  description: Specify the pagination token that's returned by a previous request to retrieve the next page of results.
                  type: string
                  pattern: .*\S.*
                  minLength: 1
                  maxLength: 3000
      summary: Amazon Lookout for Metrics List Anomaly Group Time Series
      tags:
      - ListAnomalyGroupTimeSeries
components:
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  schemas:
    ResourceNotFoundException: {}
    ValidationException: {}
    UUID:
      type: string
      pattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
      maxLength: 63
    MetricName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
      maxLength: 256
    DimensionNameValue:
      type: object
      required:
      - DimensionName
      - DimensionValue
      properties:
        DimensionName:
          allOf:
          - $ref: '#/components/schemas/ColumnName'
          - description: The name of the dimension.
        DimensionValue:
          allOf:
          - $ref: '#/components/schemas/DimensionValue'
          - description: The value of the dimension.
      description: A dimension name and value.
    DimensionValue:
      type: string
    TimeSeries:
      type: object
      required:
      - TimeSeriesId
      - DimensionList
      - MetricValueList
      properties:
        TimeSeriesId:
          allOf:
          - $ref: '#/components/schemas/TimeSeriesId'
          - description: The ID of the metric.
        DimensionList:
          allOf:
          - $ref: '#/components/schemas/DimensionNameValueList'
          - description: The dimensions of the metric.
        MetricValueList:
          allOf:
          - $ref: '#/components/schemas/MetricValueList'
          - description: The values for the metric.
      description: Details about a metric. A metric is an aggregation of the values of a measure for a dimension value, such as <i>availability</i> in the <i>us-east-1</i> Region.
    ListAnomalyGroupTimeSeriesResponse:
      type: object
      properties:
        AnomalyGroupId:
          allOf:
          - $ref: '#/components/schemas/UUID'
          - description: The ID of the anomaly group.
        MetricName:
          allOf:
          - $ref: '#/components/schemas/MetricName'
          - description: The name of the measure field.
        TimestampList:
          allOf:
          - $ref: '#/components/schemas/TimestampList'
          - description: Timestamps for the anomalous metrics.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The pagination token that's included if more results are available.
        TimeSeriesList:
          allOf:
          - $ref: '#/components/schemas/TimeSeriesList'
          - description: A list of anomalous metrics.
    DimensionNameValueList:
      type: array
      items:
        $ref: '#/components/schemas/DimensionNameValue'
    TimeSeriesList:
      type: array
      items:
        $ref: '#/components/schemas/TimeSeries'
    TimestampList:
      type: array
      items:
        $ref: '#/components/schemas/TimestampString'
    ColumnName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
      minLength: 1
      maxLength: 63
    TimeSeriesId:
      type: string
      pattern: .*\S.*
      maxLength: 520
    NextToken:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 3000
    MetricValueList:
      type: array
      items:
        $ref: '#/components/schemas/MetricValue'
    AccessDeniedException: {}
    TimestampString:
      type: string
      pattern: ^([12]\d{3})-(1[0-2]|0[1-9])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)(Z|(\+|\-)(0\d|1[0-2]):([0-5]\d)(\[[[:alnum:]\/\_]+\])?)$
      maxLength: 60
    TooManyRequestsException: {}
    MetricValue:
      type: number
      format: double
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/lookoutmetrics/
x-hasEquivalentPaths: true
