openapi: 3.0.0
info:
  version: 2017-07-25
  x-release: v4
  title: Amazon Lookout for Metrics ActivateAnomalyDetector DescribeAlert API
  description: This is the <i>Amazon Lookout for Metrics API Reference</i>. For an introduction to the service with tutorials for getting started, visit <a href="https://docs.aws.amazon.com/lookoutmetrics/latest/dev">Amazon Lookout for Metrics Developer Guide</a>.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: lookoutmetrics
  x-aws-signingName: lookoutmetrics
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/lookoutmetrics-2017-07-25.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://lookoutmetrics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The LookoutMetrics multi-region endpoint
- url: https://lookoutmetrics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The LookoutMetrics multi-region endpoint
- url: http://lookoutmetrics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The LookoutMetrics endpoint for China (Beijing) and China (Ningxia)
- url: https://lookoutmetrics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The LookoutMetrics endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: DescribeAlert
paths:
  /DescribeAlert:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeAlert
      description: <p>Describes an alert.</p> <p>Amazon Lookout for Metrics API actions are eventually consistent. If you do a read operation on a resource immediately after creating or modifying it, use retries to allow time for the write operation to complete.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeAlertResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '484':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - AlertArn
              properties:
                AlertArn:
                  description: The ARN of the alert to describe.
                  type: string
                  pattern: arn:([a-z\d-]+):.*:.*:.*:.+
                  maxLength: 256
      summary: Amazon Lookout for Metrics Describe Alert
      tags:
      - DescribeAlert
components:
  schemas:
    AlertType:
      type: string
      enum:
      - SNS
      - LAMBDA
    DimensionValue:
      type: string
    ValidationException: {}
    ResourceNotFoundException: {}
    MetricName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
      maxLength: 256
    SNSConfiguration:
      type: object
      required:
      - RoleArn
      - SnsTopicArn
      properties:
        RoleArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN of the IAM role that has access to the target SNS topic.
        SnsTopicArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN of the target SNS topic.
        SnsFormat:
          allOf:
          - $ref: '#/components/schemas/SnsFormat'
          - description: <p>The format of the SNS topic.</p> <ul> <li> <p> <code>JSON</code> – Send JSON alerts with an anomaly ID and a link to the anomaly detail page. This is the default.</p> </li> <li> <p> <code>LONG_TEXT</code> – Send human-readable alerts with information about the impacted timeseries and a link to the anomaly detail page. We recommend this for email.</p> </li> <li> <p> <code>SHORT_TEXT</code> – Send human-readable alerts with a link to the anomaly detail page. We recommend this for SMS.</p> </li> </ul>
      description: Contains information about the SNS topic to which you want to send your alerts and the IAM role that has access to that topic.
    DimensionFilter:
      type: object
      properties:
        DimensionName:
          allOf:
          - $ref: '#/components/schemas/ColumnName'
          - description: The name of the dimension to filter on.
        DimensionValueList:
          allOf:
          - $ref: '#/components/schemas/DimensionValueList'
          - description: The list of values for the dimension specified in DimensionName that you want to filter on.
      description: The dimension filter, containing DimensionName and DimensionValueList.
    MetricNameList:
      type: array
      items:
        $ref: '#/components/schemas/MetricName'
      minItems: 1
      maxItems: 5
    Alert:
      type: object
      properties:
        Action:
          allOf:
          - $ref: '#/components/schemas/Action'
          - description: Action that will be triggered when there is an alert.
        AlertDescription:
          allOf:
          - $ref: '#/components/schemas/AlertDescription'
          - description: A description of the alert.
        AlertArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN of the alert.
        AnomalyDetectorArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN of the detector to which the alert is attached.
        AlertName:
          allOf:
          - $ref: '#/components/schemas/AlertName'
          - description: The name of the alert.
        AlertSensitivityThreshold:
          allOf:
          - $ref: '#/components/schemas/SensitivityThreshold'
          - description: The minimum severity for an anomaly to trigger the alert.
        AlertType:
          allOf:
          - $ref: '#/components/schemas/AlertType'
          - description: The type of the alert.
        AlertStatus:
          allOf:
          - $ref: '#/components/schemas/AlertStatus'
          - description: The status of the alert.
        LastModificationTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time at which the alert was last modified.
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time at which the alert was created.
        AlertFilters:
          allOf:
          - $ref: '#/components/schemas/AlertFilters'
          - description: The configuration of the alert filters, containing MetricList and DimensionFilter.
      description: A configuration for Amazon SNS-integrated notifications.
    DescribeAlertResponse:
      type: object
      properties:
        Alert:
          allOf:
          - $ref: '#/components/schemas/Alert'
          - description: Contains information about an alert.
    ColumnName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
      minLength: 1
      maxLength: 63
    SensitivityThreshold:
      type: integer
      minimum: 0
      maximum: 100
    DimensionValueList:
      type: array
      items:
        $ref: '#/components/schemas/DimensionValue'
      minItems: 1
      maxItems: 10
    Arn:
      type: string
      pattern: arn:([a-z\d-]+):.*:.*:.*:.+
      maxLength: 256
    Timestamp:
      type: string
      format: date-time
    SnsFormat:
      type: string
      enum:
      - LONG_TEXT
      - SHORT_TEXT
      - JSON
    AlertFilters:
      type: object
      properties:
        MetricList:
          allOf:
          - $ref: '#/components/schemas/MetricNameList'
          - description: The list of measures that you want to get alerts for.
        DimensionFilterList:
          allOf:
          - $ref: '#/components/schemas/DimensionFilterList'
          - description: The list of DimensionFilter objects that are used for dimension-based filtering.
      description: The configuration of the alert filters.
    Action:
      type: object
      properties:
        SNSConfiguration:
          allOf:
          - $ref: '#/components/schemas/SNSConfiguration'
          - description: A configuration for an Amazon SNS channel.
        LambdaConfiguration:
          allOf:
          - $ref: '#/components/schemas/LambdaConfiguration'
          - description: A configuration for an AWS Lambda channel.
      description: A configuration that specifies the action to perform when anomalies are detected.
    LambdaConfiguration:
      type: object
      required:
      - RoleArn
      - LambdaArn
      properties:
        RoleArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN of an IAM role that has permission to invoke the Lambda function.
        LambdaArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN of the Lambda function.
      description: Contains information about a Lambda configuration.
    DimensionFilterList:
      type: array
      items:
        $ref: '#/components/schemas/DimensionFilter'
      minItems: 1
      maxItems: 5
    AlertStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    AccessDeniedException: {}
    TooManyRequestsException: {}
    InternalServerException: {}
    AlertDescription:
      type: string
      pattern: .*\S.*
      maxLength: 256
    AlertName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
      minLength: 1
      maxLength: 63
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/lookoutmetrics/
x-hasEquivalentPaths: true
